name: Run Sanity Tests on LambdaTest

on:
  workflow_dispatch:

jobs:
  sanity-test:
    runs-on: ubuntu-latest

    steps:
      - name: Trigger Sanity Test on LambdaTest
        run: |
          echo "Triggering sanity tests on LambdaTest"

          # Hardcoded Base64 encode of username:accessKey
          token=$(echo -n "anshulr:LT_Vafdmse65NnAXvVWbRuR6d0Z9Qj7xq1e9AUI2qpbgK8vamb" | base64)

          response=$(curl --location 'https://test-manager-api.lambdatest.com/api/atm/v1/hyperexecute' \
          --header "Content-Type: application/json" \
          --header "Authorization: Basic $token" \
          --data '{
            "test_run_id": "01K90AXSSG9MJ076RG6RP9FZPN",
            "concurrency": 1,
            "title": "TR-Anshul_8"
          }')

          echo "Response: $response"
