name: Run Sanity Tests on LambdaTest

on:
  push:
    branches: 
      - main

jobs:
  sanity-test:
    runs-on: ubuntu-latest

    steps:
      - name: Trigger Sanity Test on LambdaTest
        id: trigger-test
        run: |
          echo "Triggering sanity tests on LambdaTest"

          AUTH=$(echo -n "${{ secrets.LT_USERNAME }}:${{ secrets.LT_ACCESS_KEY }}" | base64)

          response=$(curl --location 'https://test-manager-api.lambdatest.com/api/atm/v1/hyperexecute' \
          --header 'Content-Type: application/json' \
          --header "Authorization: Basic $AUTH" \
          --data '{
            "test_run_id": "'"${{ secrets.TEST_RUN_ID }}"'",
            "concurrency": 1
          }')

          echo "Response: $response"

      - name: Check Test Status
        run: |
          echo "All done. ✅ Workflow triggered successfully"
