name: Run Sanity Tests on LambdaTest

on:
  workflow_dispatch:

jobs:
  sanity-test:
    runs-on: ubuntu-latest

    steps:
      - name: Upload App to LambdaTest (Real Device)
        run: |
          echo "Uploading App using download URL to LambdaTest"

          upload_response=$(curl --location 'https://manual-api.lambdatest.com/app/upload/realDevice' \
          --header 'Authorization: Basic YW5zaHVscjpMVF9WYWZkbXNlNjVObkFYdlZXYlJ1UjZkMFo5UWo3eHExZTlBVUkycXBiZ0s4dmFtYg==' \
          --form 'url="https://prod-mobile-artefacts.lambdatest.com/assets/docs/proverbial_android.apk"' \
          --form 'name="Proverbial_App"' \
          --form 'custom_id="anshul"')

          echo "Upload Response: $upload_response"
      
      - name: Wait 5 seconds
        run: |
          echo "Waiting 5 seconds to allow upload to complete"
          sleep 5
      
      - name: Trigger Sanity Test on LambdaTest
        run: |
          echo "Triggering sanity tests on LambdaTest"

          response=$(curl --location 'https://test-manager-api.lambdatest.com/api/atm/v1/hyperexecute' \
          --header 'Content-Type: application/json' \
          --header 'Authorization: Basic YW5zaHVscjpMVF9WYWZkbXNlNjVObkFYdlZXYlJ1UjZkMFo5UWo3eHExZTlBVUkycXBiZ0s4dmFtYg==' \
          --data '{
            "test_run_id": "01K94QG06P5PBMX3V926X6TFZR",
            "concurrency": 1,
            "title": "Teachfx",
            "custom_id": "anshul"
          }')

          echo "Response: $response"
